Cookbook/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Cookbook.Data;
using Cookbook.Models;
using Imgur.API.Authentication.Impl;
using Imgur.API.Endpoints.Impl;
using Imgur.API.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Cookbook.Controllers
{
    [Authorize]
    public class RecipeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _hostingEnvironment;

        public RecipeController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
             _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
        }

        public async Task<IActionResult> Edit(int id)
        {

            var recipe = await _context.Recipes.Include(a => a.IngredientsForRecipe).FirstOrDefaultAsync(m => m.RecipeId == id);
            var user = await _userManager.GetUserAsync(User);
            if (recipe != null && (user == recipe.Author || User.IsInRole("Admin")))
            {
                return View(recipe);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Recipe recipeModel)
        {
            var user = await _userManager.GetUserAsync(User);
            var recipe = await _context.Recipes.Include(i=>i.IngredientsForRecipe).FirstOrDefaultAsync(m => m.RecipeId == id);
            if (user == recipe.Author || User.IsInRole("Admin"))
            {
                TagCleaner(recipe.IngredientsForRecipe);
                TagHelper(recipeModel.IngredientsForRecipe);
                recipe.RecipeName = recipeModel.RecipeName;
                recipe.Category = recipeModel.Category;
                recipe.Abstract = recipeModel.Abstract;
                recipe.Description = recipeModel.Description;
                recipe.IngredientsForRecipe = recipeModel.IngredientsForRecipe;
                recipe.LastEditTime = DateTime.Now;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RateRecipe(int id, int rating)
        {
            var recipe = await _context.Recipes.Include(a => a.Author).Include(r => r.RatesUsers)
                .FirstOrDefaultAsync(i => i.RecipeId == id);
            var user = await _userManager.GetUserAsync(User);
            var ratedUsersId = recipe.RatesUsers.Select(i => i.Author).ToList();

            if (ratedUsersId.Contains(user))
            {
                var rates = recipe.RatesUsers.Where(i => i.Author == user).ToList();
                foreach (var rate in rates)
                {
                    recipe.RatesUsers.Remove(rate);                    
                }
            }

            recipe.RatesUsers.Add(new RateUser()
            {
                RecipeId = id,
                Author = user,
                Rate = rating
            });

            recipe.Rating = (double) recipe.RatesUsers.Sum(x => x.Rate) / recipe.RatesUsers.Count;
            
            await _context.SaveChangesAsync();

            return RedirectToAction("Details/" + id);
        }

        [HttpPost]
        public async Task<IActionResult> CommentLike(int id, int recipeId)
        {
            var comment = await _context.Comments.Include(a => a.Author).Include(l => l.CommentLikes)
                .FirstOrDefaultAsync(i => i.CommentId == id);
            var user = await _userManager.GetUserAsync(User);

            var likedUsersId = comment.CommentLikes.Select(i => i.Author).ToList();

            if (likedUsersId.Contains(user))
            {
                comment.Likes -= 1;
                var like = await _context.CommentLikes.FirstOrDefaultAsync(i => i.Author == user);
                comment.CommentLikes.Remove(like);
            }
            else
            {
                comment.Likes += 1;
                comment.CommentLikes.Add(new CommentLike()
                {
                    Author = user,
                    CommentId = id
                });
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Details/" + recipeId);
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(int postId, Recipe recipe)
        {
            var commentedRecipe = await _context.Recipes.FirstOrDefaultAsync(m => m.RecipeId == postId);
            if (commentedRecipe == null)
            {
                return NotFound();
            }

            commentedRecipe.CurrentComment = recipe.CurrentComment;

            _context.Comments.Add(new Comment()
            {
                RecipeId = postId,
                Author = await _userManager.GetUserAsync(User),
                CreatedDate = DateTime.UtcNow,
                Text = recipe.CurrentComment
            });
            await _context.SaveChangesAsync();
            LuceneSearch.AddUpdateLuceneIndexComment(commentedRecipe);
            return Redirect("Details/" + postId);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(string sortBy)
        {
            var viewModel = new RecipeIndexViewModel();
            if (sortBy == null)
            {
                viewModel.Recipes = await _context.Recipes.Include(a => a.Author).OrderByDescending(t=>t.LastEditTime).ToListAsync();
            }
            if (sortBy == "rating")
            {
                viewModel.Recipes = await _context.Recipes.Include(a => a.Author).OrderByDescending(r=>r.Rating).ToListAsync();
            }
            if (sortBy == "name")
            {
                viewModel.Recipes = await _context.Recipes.Include(a => a.Author).OrderBy(n => n.RecipeName).ToListAsync();
            }
            if (sortBy == "date")
            {
                viewModel.Recipes = await _context.Recipes.Include(a => a.Author).OrderBy(t=>t.LastEditTime).ToListAsync();
            }

            viewModel.Tags = await _context.Tags.ToListAsync();
            return View(viewModel);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Categories()
        {
            var categories = await _context.Recipes.Select(c => c.Category).Distinct().OrderBy(x=>x).ToListAsync();
            return View(categories);
        }

        [AllowAnonymous]
        public async Task<IActionResult> SortByCategory(string id)
        {
            var viewModel = new CategoryViewModel
            {
                CategoryName = id,
                Recipes = await _context.Recipes.Include(a => a.Author).Where(c => c.Category == id).ToListAsync()
            };


            return View(viewModel);
        }

        [AllowAnonymous]
        public async Task<IActionResult> SortByTag(int id)
        {
            var viewModel = new RecipeIndexViewModel();

            var tag = await _context.Tags.FirstOrDefaultAsync(i => i.TagId == id);
            var recipesId = await _context.IngredientForRecipes.Where(n => n.IngredientName == tag.TagName)
                .Select(i => i.RecipeId).Distinct().ToListAsync();

            viewModel.Recipes = await _context.Recipes.Include(a => a.Author).Where(i => recipesId.Contains(i.RecipeId)).ToListAsync();

            viewModel.Tags = new List<Tag>() {tag};

            return View(viewModel);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var post = await _context.Recipes.Include(a => a.Author).Include(i =>i.IngredientsForRecipe).FirstOrDefaultAsync(m => m.RecipeId == id);

            if (post == null)
            {
                return NotFound();
            }

            var comments = _context.Comments.Include(a=>a.Author).Where(x => x.RecipeId == id).ToList();
            post.Comments = comments;

            return View(post);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                TagHelper(recipe.IngredientsForRecipe);
                recipe.LastEditTime = DateTime.Now;
                recipe.Author = await _userManager.GetUserAsync(User);
                _context.Add(recipe);
                await _context.SaveChangesAsync();
                LuceneSearch.AddUpdateLuceneIndex(recipe);
                return RedirectToAction("Index");
            }
            return View(recipe);
        }

        public async Task<IActionResult> Delete(int id)
        {

            var recipe = await _context.Recipes.FirstOrDefaultAsync(m => m.RecipeId == id);
            var user = await _userManager.GetUserAsync(User);
            if (recipe != null && (user == recipe.Author || User.IsInRole("Admin")))
            {
                return View(recipe);
            }

            return NotFound();
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, ApplicationUser user)
        {
            var recipe = await _context.Recipes.Include(a => a.RatesUsers).Include(a => a.Comments)
                            .Include(a => a.Author).Include(i=>i.IngredientsForRecipe).FirstOrDefaultAsync(m => m.RecipeId == id);

            if (user == null)
            {
                user = await _userManager.GetUserAsync(User);
            }

            if (user == recipe.Author || User.IsInRole("Admin"))

Cookbook/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cookbook.Data;
using Cookbook.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace Cookbook.Controllers
{
    public class SearchController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SearchController(ApplicationDbContext context)
        {
            _context = context;
        }

        public ActionResult Index(string id)
        {
            var recipesId = LuceneSearch.Search(id, null).Select(i=>i.RecipeId).ToList();
            List<Recipe> findRecipes = new List<Recipe>();
            foreach (var recipeId in recipesId)
            {
                var recipe = _context.Recipes.Include(a => a.Author).FirstOrDefault(i => i.RecipeId == recipeId);
                findRecipes.Add(recipe);
            }
            return View(findRecipes);
        }
    }
}

Cookbook/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cookbook</title>

    <environment include="Development">
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        @{if (Context.Request.Cookies["theme"] == null || Context.Request.Cookies["theme"] == "green")
            {
                <link rel="stylesheet" href="~/css/theme1.css" />
            }
            else
            {
                <link rel="stylesheet" href="~/css/theme2.css" />
            }
        }

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
<nav>
    <div class="nav-wrapper">
        <div class="nav-left">
            <a asp-area="" asp-controller="Recipe" asp-action="Index" class="brand-logo">Cookbook</a>
            <ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <li><a asp-area="" asp-controller="Recipe" asp-action="Create">@Localizer["Create"]</a></li>
                }
                <li><a asp-area="" asp-controller="Recipe" asp-action="Categories">@Localizer["Categories"]</a></li>
                @if (User.IsInRole("Admin"))
                {
                    <li>
                        <a asp-area="" asp-controller="Manage" asp-action="UserList">@Localizer["UserList"]</a>
                    </li>
                }
            </ul>
        </div>

        <form asp-controller="Search" asp-action="Index">
            <ul class="hide-on-med-and-down categories">
                <li style="width: 300px;">
                    <input class="form-control" id="id" name="id" type="text" />
                </li>
                <li>
                    <button type="submit" class="btn btn-default">Поиск</button>
                </li>              
            </ul>
        </form>
        @await Html.PartialAsync("_LoginPartial")
    </div>
</nav>


<div class="container body-content">
    @RenderBody()
        
</div>

<hr />
<footer>
    <p>&copy; 2019 - Cookbook</p>
</footer>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/materialize/materialize.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</environment>

    @RenderSection("Scripts", required: false)


    <script>
        M.AutoInit();
    </script>

</body>
</html>